# Generated by Django 3.1.6 on 2021-02-12 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Main dashboard', help_text='Name for the dashboard', max_length=120)),
                ('description', models.CharField(max_length=255)),
                ('viz_type', models.CharField(choices=[('bar_chart', 'Bar chart')], default='bar_chart', help_text='The type of chartjs chart used', max_length=20)),
                ('params', models.JSONField(default=dict)),
            ],
        ),
    ]
